name: Build image

on:
  push:

jobs:
  build_image:
    name: Build image with buildah
    runs-on: ubuntu-24.04

    steps:
      - name: test
        run: ls

      - name: Run build
        run: buildah build -f Containerfile
